REPO_BASE_DIR := $(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST)../../..))))

# TARGETS --------------------------------------------------
include ${REPO_BASE_DIR}/scripts/common.Makefile
.DEFAULT_GOAL := help
