services:
  dy-static-file-server:
    build:
      labels:
        io.simcore.authors: '{"authors": [{"name": "Sylvain Anderegg", "email": "anderegg@itis.swiss",
          "affiliation": "IT''IS Foundation"}]}'
        io.simcore.contact: '{"contact": "anderegg@itis.swiss"}'
        io.simcore.description: '{"description": "Legacy test dynamic service (starts
          using original director-v0)"}'
        io.simcore.inputs: '{"inputs": {}}'
        io.simcore.integration-version: '{"integration-version": "1.0.0"}'
        io.simcore.key: '{"key": "simcore/services/dynamic/dy-static-file-server"}'
        io.simcore.name: '{"name": "dy-static-file-server"}'
        io.simcore.outputs: '{"outputs": {}}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.version: '{"version": "1.0.4"}'
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ${VCS_REF}
        org.label-schema.vcs-url: ${VCS_URL}
        simcore.service.settings: '[{"name": "resources", "type": "Resources", "value":
          {"mem_limit":17179869184, "cpu_limit": 1000000000}}, {"name": "ports", "type":
          "int", "value": 80}, {"name": "constraints", "type": "string", "value":
          ["node.platform.os == linux"]}]'
  dy-static-file-server-dynamic-sidecar:
    build:
      labels:
        io.simcore.authors: '{"authors": [{"name": "Sylvain Anderegg", "email": "anderegg@itis.swiss",
          "affiliation": "IT''IS Foundation"}]}'
        io.simcore.contact: '{"contact": "anderegg@itis.swiss"}'
        io.simcore.description: '{"description": "Modern test dynamic service (with
          dynamic sidecar)"}'
        io.simcore.inputs: '{"inputs": {}}'
        io.simcore.integration-version: '{"integration-version": "1.0.0"}'
        io.simcore.key: '{"key": "simcore/services/dynamic/dy-static-file-server-dynamic-sidecar"}'
        io.simcore.name: '{"name": "dy-static-file-server-dynamic-sidecar"}'
        io.simcore.outputs: '{"outputs": {}}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.version: '{"version": "1.0.4"}'
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ${VCS_REF}
        org.label-schema.vcs-url: ${VCS_URL}
        simcore.service.paths-mapping: '{"outputs_path": "/www/outputs", "inputs_path":
          "/www/inputs"}'
        simcore.service.settings: '[{"name": "resources", "type": "Resources", "value":
          {"mem_limit":17179869184, "cpu_limit": 1000000000}}, {"name": "ports", "type":
          "int", "value": 80}, {"name": "constraints", "type": "string", "value":
          ["node.platform.os == linux"]}]'
  dy-static-file-server-dynamic-sidecar-compose-spec:
    build:
      labels:
        io.simcore.authors: '{"authors": [{"name": "Sylvain Anderegg", "email": "anderegg@itis.swiss",
          "affiliation": "IT''IS Foundation"}]}'
        io.simcore.contact: '{"contact": "anderegg@itis.swiss"}'
        io.simcore.description: '{"description": "Modern test dynamic service providing
          a docker-compose specificaiton file (with dynamic sidecar and compose-spec)"}'
        io.simcore.inputs: '{"inputs": {}}'
        io.simcore.integration-version: '{"integration-version": "1.0.0"}'
        io.simcore.key: '{"key": "simcore/services/dynamic/dy-static-file-server-dynamic-sidecar-compose-spec"}'
        io.simcore.name: '{"name": "dy-static-file-server-dynamic-sidecar-compose-spec"}'
        io.simcore.outputs: '{"outputs": {}}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.version: '{"version": "1.0.4"}'
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ${VCS_REF}
        org.label-schema.vcs-url: ${VCS_URL}
        simcore.service.compose-spec: ${DOCKER_COMPOSE_SPECIFICATION}
        simcore.service.container-http-entrypoint: dy-static-file-server-dynamic-sidecar-compose-spec
        simcore.service.paths-mapping: '{"outputs_path": "/www/outputs", "inputs_path":
          "/www/inputs"}'
        simcore.service.settings: '[{"name": "resources", "type": "Resources", "value":
          {"mem_limit":17179869184, "cpu_limit": 1000000000}}, {"name": "ports", "type":
          "int", "value": 80}, {"name": "constraints", "type": "string", "value":
          ["node.platform.os == linux"]}]'
version: '3.7'
