version: "3.7"
services:
  dy-static-file-server-dynamic-sidecar-compose-spec:
    init: true
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}-dynamic-sidecar-compose-spec:${DOCKER_IMAGE_TAG}
    environment:
      - MOCK_VALUE=TheMockedValue

  some-side-service:
    init: true
    image: busybox:latest
    cmd: top
