version: "3.7"
services:
  dy-static-file-server-dynamic-sidecar-compose-spec:
    init: true
    # - SIMCORE_REGISTRY will be replaced by the url of the simcore docker registry 
    # deployed inside the platform
    # - SERVICE_VERSION will be replaced by the version of the service
    # to which this compos spec is attached
    image: ${SIMCORE_REGISTRY}/${DOCKER_IMAGE_NAME}-dynamic-sidecar-compose-spec:${SERVICE_VERSION}
    environment:
      - MOCK_VALUE=TheMockedValue

  some-side-service:
    init: true
    image: busybox:latest
    cmd: top
