#!/bin/bash
set -e
cd $(dirname $0)

echo "deleting ${DOCKER_REGISTRY}/${DOCKER_PROJECT}"

DOCKER_TAG=$(./docker-registry-curl https://${DOCKER_REGISTRY}/v2/${DOCKER_PROJECT}/tags/list | jq -r .tags[0])
while [ "${DOCKER_TAG}" != "null" ]
do
    echo "${DOCKER_PROJECT}:${DOCKER_TAG}..."
    export DOCKER_ETAG=$(./docker-registry-curl -I -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -X GET "https://${DOCKER_REGISTRY}/v2/${DOCKER_PROJECT}/manifests/${DOCKER_TAG}" | egrep -e "Docker-Content-Digest: " | cut -d " " -f2 | tr -d \" | sed 's/\r//')
    ./docker-registry-curl -X DELETE "https://${DOCKER_REGISTRY}/v2/${DOCKER_PROJECT}/manifests/${DOCKER_ETAG}"
    DOCKER_TAG=$(./docker-registry-curl https://${DOCKER_REGISTRY}/v2/${DOCKER_PROJECT}/tags/list | jq -r .tags[0])
done

