version: "3.7"
services:
  sleeper:
    image: local/${DOCKER_IMAGE_NAME}:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production
      args:
        BASE_IMAGE: python:${PYTHON_VERSION}-slim
        PYTHON_VERSION: ${PYTHON_VERSION}

  sleeper-gpu:
    image: local/${DOCKER_IMAGE_NAME}-gpu:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production
      args:
        BASE_IMAGE: nvidia/cuda:13.3.1-base-ubuntu26.04
        PYTHON_VERSION: ${PYTHON_VERSION}
  sleeper-mpi:
    image: local/${DOCKER_IMAGE_NAME}-mpi:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production
      args:
        BASE_IMAGE: nvidia/cuda:13.3.1-base-ubuntu26.04
        PYTHON_VERSION: ${PYTHON_VERSION}
