version: "3.7"
services:
  sleeper:
    image: local/${DOCKER_IMAGE_NAME}:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production
      args:
        BASE_IMAGE: python:3.11-slim

  sleeper-gpu:
    image: local/${DOCKER_IMAGE_NAME}-gpu:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production
      args:
        INSTALL_EXTRAS: true
        BASE_IMAGE: nvidia/cuda:12.3.1-base-ubuntu22.04
  sleeper-mpi:
    image: local/${DOCKER_IMAGE_NAME}-mpi:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production
      args:
        INSTALL_EXTRAS: true
        BASE_IMAGE: nvidia/cuda:12.3.1-base-ubuntu22.04
