version: "3.7"
services:
  jupyter-base-notebook:
    image: jupyter-base-notebook-dev
    build:
      target: development
    environment:
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - USE_CASE_CONFIG_FILE=devel/port_config.json
      - TEST_DATA_PATH=/home/jovyan/test-data
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
    depends_on:
      - storage
      - postgres
    ports:
      - "8888:8888"
    volumes:
      - ../../services/:/home/jovyan/services
      - ./handlers:/home/jovyan/handlers
      - ./devel:/home/jovyan/devel
      - ../../scripts/dy_services_helpers:/home/jovyan/scripts/dy_services_helpers
      - ./notebooks:/home/jovyan/notebooks
      - ./docker:/docker
      - ./retrieval-data:/home/jovyan/test-data
      - ./notebook-inputs:/home/jovyan/inputs
      - ./notebook-outputs:/home/jovyan/outputs
  # --------------------------------------------------------------------
  jupyter-scipy-notebook:
    image: jupyter-scipy-notebook-dev
    build:
      target: development
    environment:
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - USE_CASE_CONFIG_FILE=devel/port_config.json
      - TEST_DATA_PATH=/home/jovyan/test-data
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
    depends_on:
      - storage
      - postgres
    ports:
      - "8889:8888"
    volumes:
      - ../../services/:/home/jovyan/services
      - ./handlers:/home/jovyan/handlers
      - ./devel:/home/jovyan/devel
      - ../../scripts/dy_services_helpers:/home/jovyan/scripts/dy_services_helpers
      - ./notebooks:/home/jovyan/notebooks
      - ./docker:/docker
      - ./retrieval-data:/home/jovyan/test-data
      - ./notebook-inputs:/home/jovyan/inputs
      - ./notebook-outputs:/home/jovyan/outputs
  #--------------------------------------------------------------------
  jupyter-r-notebook:
    image: jupyter-r-notebook-dev
    build:
      target: development
    environment:
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - USE_CASE_CONFIG_FILE=devel/port_config.json
      - TEST_DATA_PATH=/home/jovyan/test-data
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
    depends_on:
      - storage
      - postgres
    ports:
      - "8890:8888"
    volumes:
      - ../../services/:/home/jovyan/services
      - ./handlers:/home/jovyan/handlers
      - ./devel:/home/jovyan/devel
      - ../../scripts/dy_services_helpers:/home/jovyan/scripts/dy_services_helpers
      - ./notebooks:/home/jovyan/notebooks
      - ./docker:/docker
      - ./retrieval-data:/home/jovyan/test-data
      - ./notebook-inputs:/home/jovyan/inputs
      - ./notebook-outputs:/home/jovyan/outputs
  #--------------------------------------------------------------------
  storage:
    image: itisfoundation/storage:latest
    init: true
    ports:
      - 11111:8080
    environment:
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - STORAGE_LOGLEVEL=${LOG_LEVEL:-WARNING}
      - STORAGE_MONITORING_ENABLED=1
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_SECURE=${S3_SECURE}
      - BF_API_SECRET=${BF_API_SECRET}
      - BF_API_KEY=${BF_API_KEY}
      - TRACING_ENABLED=${TRACING_ENABLED:-True}
      - TRACING_ZIPKIN_ENDPOINT=${TRACING_ZIPKIN_ENDPOINT:-http://jaeger:9411}
    restart: always
    depends_on:
      - postgres
      - minio
  #--------------------------------------------------------------------
  postgres:
    image: postgres:10
    init: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  #--------------------------------------------------------------------
  adminer:
    image: adminer
    init: true
    ports:
      - 18080:8080
    depends_on:
      - postgres
  #--------------------------------------------------------------------
  minio:
    image: minio/minio
    init: true
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "9001:9000"
    command: server /data
