version: '3.7'
services:
  httpbin:
    init: true
    image: ${DOCKER_REGISTRY}/httpbin:${DOCKER_IMAGE_TAG}
  httpbin-dynamic-sidecar:
      init: true
      image: ${DOCKER_REGISTRY}/httpbin-dynamic-sidecar:${DOCKER_IMAGE_TAG}

  httpbin-dynamic-sidecar-compose:
      init: true
      image: ${DOCKER_REGISTRY}/httpbin-dynamic-sidecar-compose:${DOCKER_IMAGE_TAG}
