FROM itisfoundation/3d-viewer:3.0.3 as threed-viewer

FROM itisfoundation/3d-viewer-gpu:3.0.3 as threed-viewer-gpu

FROM itisfoundation/cc-0d-viewer:3.0.4 as cc-0d-viewer

FROM itisfoundation/cc-1d-viewer:3.0.4 as cc-1d-viewer

FROM itisfoundation/cc-2d-viewer:3.0.5 as cc-2d-viewer

FROM itisfoundation/csv-table:1.0.0 as csv-table

FROM itisfoundation/dy-static-file-server:2.0.4 as dy-static-file-server

FROM itisfoundation/dy-static-file-server-dynamic-sidecar:2.0.4 as dy-static-file-server-dynamic-sidecar

FROM itisfoundation/dy-static-file-server-dynamic-sidecar-compose-spec:2.0.4 as dy-static-file-server-dynamic-sidecar-compose-spec

FROM itisfoundation/jupyter-base-notebook:2.14.0 as jupyter-base-notebook

FROM itisfoundation/jupyter-neuron:1.1.0 as jupyter-neuron

FROM itisfoundation/jupyter-r-notebook:2.14.0 as jupyter-r-notebook

FROM itisfoundation/jupyter-scipy-notebook:2.14.0 as jupyter-scipy-notebook

FROM itisfoundation/kember-viewer:2.14.0 as kember-viewer

FROM itisfoundation/mapcore-widget:0.1.24 as mapcore-widget

FROM itisfoundation/mattward-viewer:3.0.5 as mattward-viewer

FROM itisfoundation/raw-graphs:2.11.1 as raw-graphs

FROM itisfoundation/raw-graphs-table:2.11.1 as raw-graphs-table

FROM itisfoundation/tissue-properties:1.0.1 as tissue-properties
