FROM itisfoundation/cc-rabbit-0d:3.0.4 as cc-rabbit-0d

FROM itisfoundation/cc-rabbit-1d:3.0.4 as cc-rabbit-1d

FROM itisfoundation/cc-rabbit-2d:3.0.5 as cc-rabbit-2d

FROM itisfoundation/csv-table:1.0.0 as csv-table

FROM itisfoundation/dy-static-file-server:2.0.4 as dy-static-file-server

FROM itisfoundation/dy-static-file-server-dynamic-sidecar:2.0.4 as dy-static-file-server-dynamic-sidecar

FROM itisfoundation/dy-static-file-server-dynamic-sidecar-compose-spec:2.0.4 as dy-static-file-server-dynamic-sidecar-compose-spec

FROM itisfoundation/jupyter-base-notebook:2.14.0 as jupyter-base-notebook

FROM itisfoundation/jupyter-neuron:1.1.0 as jupyter-neuron

FROM itisfoundation/jupyter-r-notebook:2.14.0 as jupyter-r-notebook

FROM itisfoundation/jupyter-scipy-notebook:2.14.0 as jupyter-scipy-notebook

FROM itisfoundation/kember:2.14.0 as kember

FROM itisfoundation/mapcore-widget:0.1.24 as mapcore-widget

FROM itisfoundation/mattward-dash:3.0.5 as mattward-dash

FROM itisfoundation/raw-graphs:2.11.1 as raw-graphs

FROM itisfoundation/raw-graphs-table:2.11.1 as raw-graphs-table

FROM itisfoundation/server:0.1.1 as server

FROM itisfoundation/tissue-properties:1.0.1 as tissue-properties
