version: "3.7"
services:
  opencorservice_demo:
    image: local/${DOCKER_IMAGE_NAME}:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/ubuntu/Dockerfile
      target: production
