version: '3.4'
services:
  mattward-dash:
    image: services_mattward-viewer-dev-dash
    build:
      target: development
    environment:
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - USE_CASE_CONFIG_FILE=devel-config/port_config.json
      - INIT_OPTIONS=100 6000 20 space
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
    volumes:
      - ../../../scripts/dy_services_helpers:/home/jovyan/scripts/dy_services_helpers
      - ./mattward/src:/home/jovyan/src
      - ./mattward/input:/home/jovyan/input
      - ./mattward/output:/home/jovyan/output
      - ./mattward/devel-config:/home/jovyan/devel-config
      - ../../../services:/home/jovyan/services
    depends_on:
      - postgres
      - minio
  bornstein:
    image: services_bornstein-viewer-dev
    build:
      target: development
    environment:
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - USE_CASE_CONFIG_FILE=devel-config/port_config.json
      - INIT_OPTIONS=100 6000 20 space
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
    volumes:
      - ../../../scripts/dy_services_helpers:/home/jovyan/scripts/dy_services_helpers
      - ./bornstein/app:/home/jovyan/app
      - ./bornstein/input:/home/jovyan/input
      - ./bornstein/output:/home/jovyan/output
      - ./bornstein/devel-config:/home/jovyan/devel-config
      - ../../../services:/home/jovyan/services
    depends_on:
      - postgres
      - minio
  #--------------------------------------------------------------------
  apihub:
    image: itisfoundation/apihub:staging-latest
    ports:
      - 8043:8043
  #--------------------------------------------------------------------
  storage:
    image: itisfoundation/storage:staging-latest
    ports:
      - 11111:8080
    environment:
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_SECURE=${S3_SECURE}
      - BF_API_SECRET=none
      - BF_API_KEY=none
      - APIHUB_HOST=${APIHUB_HOST}
      - APIHUB_PORT=${APIHUB_PORT}

    restart: always
    depends_on:
      - postgres
      - apihub
  #--------------------------------------------------------------------
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  #--------------------------------------------------------------------
  adminer:
    image: adminer
    ports:
      - 18080:8080
    depends_on:
       - postgres
  #--------------------------------------------------------------------
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "9001:9000"
    command: server /data
