version: "3.7"
services:
  cardiac_myocyte_grandi:
    image: local/${DOCKER_IMAGE_NAME}:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production
