version: '3.6'
services:
  tissue-properties:
    image: ${DOCKER_REGISTRY}/tissue-properties:${DOCKER_IMAGE_TAG}
    build:
      context: ../../
      dockerfile: services/dy-tissue-properties/Dockerfile
      target: production
      labels:
        io.simcore.key: '{"key": "simcore/services/dynamic/tissue-properties"}'
        io.simcore.version: '{"version": "${DOCKER_IMAGE_TAG}"}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.name: '{"name": "Tissue properties"}'
        io.simcore.description: '{"description": "Tissue properties powered by [ITIS Foundation](https://itis.swiss/virtual-population/tissue-properties/overview/) and [csv-to-html-table](https://github.com/derekeder/csv-to-html-table)"}'
        io.simcore.authors: '{"authors": [{"name": "odeimaiz", "email": "maiz@itis.swiss", "affiliation": "ITIS Foundation"}]}'
        io.simcore.contact: '{"contact": "maiz@itis.swiss"}'
        io.simcore.inputs: '{"inputs": {}}'
        io.simcore.outputs: '{"outputs": {"output_1": {"label": "Tissue Properties", "displayOrder":
          0, "description": "Input data csv", "type": "data:text/csv", "fileToKeyMap":
          {"input.csv": "output_1"}}}}'
        simcore.service.settings: '[{"name": "resources", "type": "Resources", "value": {"mem_limit":17179869184, "cpu_limit": 4000000000}}, {"name": "ports", "type": "int", "value": 4000}, {"name": "constraints", "type": "string", "value": ["node.platform.os == linux"]}]'
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
    environment:
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
      - TISSUEPROPS_INPUT_PATH=${TISSUEPROPS_INPUT_PATH}
      - TISSUEPROPS_OUTPUT_PATH=${TISSUEPROPS_OUTPUT_PATH}
    ports:
      - '4000:4000'
