version: '3.7'
services:
  cc-rabbit-0d:
    build:
      target: development
    security_opt:
      # in case gdb is needed
      - seccomp:unconfined
    environment:
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - USE_CASE_CONFIG_FILE=/home/jovyan/devel-config/port_config.json
      - TEST_DATA_PATH=/home/jovyan/input
      - INIT_OPTIONS=100 6000 20 space
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
    volumes:
      # mount the sources by default
      - ./src/cc-rabbit-0d:/home/jovyan/src
      - ../../../scripts/dy_services_helpers:/home/jovyan/scripts/dy_services_helpers
      - ./validation/input:/home/jovyan/input
      - ./validation/output:/home/jovyan/output
      - ./devel-config:/home/jovyan/devel-config
    depends_on:
      - postgres
      - minio
      - adminer
      - storage
  #--------------------------------------------------------------------
  apihub:
    image: itisfoundation/apihub:staging-latest
    init: true
    ports:
      - 8043:8043
  #--------------------------------------------------------------------
  storage:
    image: itisfoundation/storage:staging-latest
    init: true
    ports:
      - 11111:8080
    environment:
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_SECURE=${S3_SECURE}
      - BF_API_SECRET=none
      - BF_API_KEY=none
      - APIHUB_HOST=${APIHUB_HOST}
      - APIHUB_PORT=${APIHUB_PORT}

    restart: always
    depends_on:
      - postgres
      - apihub
  #--------------------------------------------------------------------
  postgres:
    image: postgres:10
    init: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  #--------------------------------------------------------------------
  adminer:
    image: adminer
    init: true
    ports:
      - 18080:8080
    depends_on:
      - postgres
  #--------------------------------------------------------------------
  minio:
    image: minio/minio
    init: true
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "9001:9000"
    command: server /data
