# TODO: Please set your custom image here and adapt the Dockerfile/entrypoint.sh accordingly
FROM halverneus/static-file-server:v1.8.3 as production 
#
#  USAGE:
#     cd services/dy-static-file-server
#     docker build -f Dockerfile -t dy-static-file-server:prod --target production ../../
#     docker run dy-static-file-server:prod
#

LABEL maintainer=sanderegg


# ENTRYPOINT [ "/bin/sh", "docker/entrypoint.sh", "/bin/sh", "-c" ]
