#!/bin/bash
cd $(dirname $0)
# ----------------------------------------------------------------
# This script shall be modified according to the needs in order to run the service
# The inputs defined in docker/inputs.json are available as env variables by their key in capital letters
# For example: input_1 -> $INPUT_1
# call stack:
# run -> do_run -> execute

set -e
cd /home/scu/cc-rabbit-0d
# put the code to execute the service here
# and default all outputs to $LOG_FILE
# For example: java someJavaClass >> $LOG_FILE

# then retrieve the output and move it to the $OUTPUT_FOLDER
# as defined in the output labels
# For example: cp output.csv $OUTPUT_FOLDER or to $OUTPUT_FOLDER/output.json using jq
#TODO: Replace following
cat > $OUTPUT_FOLDER/output.json << EOF
{

    "output_1":"some_stuff"
,
    "output_2":"some_stuff"
,
    "output_3":"some_stuff"
,
    "output_4":"some_stuff"
,
    "output_5":"some_stuff"
,
    "output_6":"some_stuff"
,
    "output_7":"some_stuff"
,
    "output_8":"some_stuff"
,
    "output_9":"some_stuff"
,
    "output_10":"some_stuff"
,
    "output_11":"some_stuff"
,
    "output_12":"some_stuff"
,
    "output_13":"some_stuff"
,
    "output_14":"some_stuff"
,
    "output_15":"some_stuff"
,
    "output_16":"some_stuff"
,
    "output_17":"some_stuff"
,
    "output_18":"some_stuff"

}
EOF

