version: '3.4'
services:
  jupyter-neuron:
    image: jupyter-neuron-dev
    build:
      target: development
    environment:
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
    volumes:
      - ../../../scripts/dy_services_helpers:/home/jovyan/scripts/dy_services_helpers
      - ./notebooks:/home/jovyan/notebooks
    depends_on:
      - postgres
      - minio 
    #--------------------------------------------------------------------
  apihub:
    image: itisfoundation/apihub:staging-latest
    ports:
      - 8043:8043
  #--------------------------------------------------------------------
  storage:
    image: itisfoundation/storage:staging-latest
    ports:
      - 11111:8080
    environment:
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_SECURE=${S3_SECURE}
      - BF_API_SECRET=none
      - BF_API_KEY=none
      - APIHUB_HOST=${APIHUB_HOST}
      - APIHUB_PORT=${APIHUB_PORT}

    restart: always
    depends_on:
      - postgres
      - apihub
  #--------------------------------------------------------------------
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  #--------------------------------------------------------------------
  adminer:
    image: adminer
    ports:
      - 18080:8080
    depends_on:
      - postgres
  #--------------------------------------------------------------------
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "9001:9000"
    command: server /data
