name: Github-CI Push/PR dy-static-file-server

on:
  push:
    paths:
      - "services/dy-static-file-server/**"
      - "!**.md"
  pull_request:
    paths:
      - "services/dy-static-file-server/**"
      - "!**.md"

env:
  # secrets can be set in settings/secrets on github
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: building dy-static-file-server
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.8]
        os: [ubuntu-18.04]
        node: [10]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: show versions
        run: ./ci/helpers/show_system_versions.bash
      - uses: actions/cache@v2
        name: getting cached data
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: set owner variable
        run: echo "OWNER=${GITHUB_REPOSITORY%/*}" >> $GITHUB_ENV
      - name: set docker image tag
        if: github.ref != 'refs/heads/master'
        run: echo "DOCKER_IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: set dev environs
        working-directory: services/dy-static-file-server
        run: make devenv
      - name: get current image if available
        working-directory: services/dy-static-file-server
        run: make pull-latest || true
      - name: build
        working-directory: services/dy-static-file-server
        run: |
          make build-x
          make info-build
      - name: test
        working-directory: services/dy-static-file-server
        run: make tests
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: deploy
        working-directory: services/dy-static-file-server
        run: |
          ./../../ci/helpers/dockerhub_login.bash
          make push
      - if: github.event_name == 'push' && github.ref != 'refs/heads/master'
        name: deploy
        working-directory: services/dy-static-file-server
        run: |
          ./../../ci/helpers/dockerhub_login.bash
          make push-version
